- JY/DAY1/BOJ_1000.java
- JY/DAY1/BOJ_10905.java
- JY/DAY1/BOJ_11021.java
- JY/DAY1/BOJ_2558.java
> DAY1 : 입출력

- JY/DAY4/BOJ_2751.java
- JY/DAY5/BOJ_10989.java
- JY/DAY5/BOJ_11650.java
- JY/DAY5/BOJ_11651.java
- JY/DAY5/BOJ_11652.java
> DAY4 + DAY 5 : DP, sorting

- JY/DAY5/BOJ_11004.java
- JY/DAY6/BOJ_10828.java
- JY/DAY6/BOJ_9012.java
> DAY 5 : sorting, stack

- JY/DAY6/BOJ_10799.java
- JY/DAY6/BOJ_10808.java
- JY/DAY6/BOJ_10845.java
> [JY] DAY 6 : stack, queue

- JY/DAY8/BOJ_10430.java
- JY/DAY8/BOJ_11005.java
- JY/DAY8/BOJ_1158.java
- JY/DAY8/BOJ_1168.java
- JY/DAY8/BOJ_1373.java
- JY/DAY8/BOJ_1406.java
- JY/DAY8/BOJ_1850.java
- JY/DAY8/BOJ_1934.java
- JY/DAY8/BOJ_2609.java
- JY/DAY8/BOJ_2745.java
- JY/DAY8/BOJ_9613.java
> [JY] DAY 8 : Mathematics

- JY/DAY10/BOJ_1260.py
- JY/DAY10/BOJ_1707.py
> [JY ]DAY10 : graph

- JY/DAY11/BOJ_10451.py
- JY/DAY11/BOJ_10825.py
- JY/DAY11/BOJ_11651.py
- JY/DAY11/BOJ_2331.py
- JY/DAY11/BOJ_2667.py
- JY/DAY11/BOJ_2751.py
- JY/DAY11/BOJ_9466.py
> [JY ] DAY11 

- JY/DAY12/BOJ_10814.py
- JY/DAY12/BOJ_20920.py
- JY/DAY12/BOJ_4963.py
- JY/DAY12/BOJ_7576.py
> [JY] DAY12 : sorting, Graph

- JY/DAY13/BOJ_11725.py
- JY/DAY13/BOJ_1991.py
- JY/DAY13/BOJ_2146.py
- JY/DAY13/BOJ_2178.py
> [JY] DAY13 : graph

- HY/Day 11/1260.py
> feat: solve Day11

- JY/DAY14/BOJ_1167.py
- JY/DAY14/BOJ_1654.py
- JY/DAY14/BOJ_2110.py
- JY/DAY14/BOJ_2805.py
> [JY] DAY14 : 이분탐색

- JY/DAY15/BOJ_10815.py
- JY/DAY15/BOJ_10816.py
- JY/DAY15/BOJ_11047.py
- JY/DAY15/BOJ_11728.py
> [JY] DAY15 : 이분탐색, 그리디

- JY/DAY16/BOJ_10610.py
- JY/DAY16/BOJ_1783.py
- JY/DAY16/BOJ_1931.py
- JY/DAY16/BOJ_2875.py
> [JY]DAY16:그리디

- ys/src/Day2/BJ10991/Main.java
- ys/src/Day2/BJ10992/Main.java
- ys/src/Day2/BJ2440/Main.java
- ys/src/Day2/BJ2441/Main.java
- ys/src/Day2/BJ2442/Main.java
- ys/src/Day2/BJ2445/Main.java
- ys/src/Day2/BJ2446/Main.java
- ys/src/Day2/BJ2522/Main.java
> feat : day2 - IO

- JY/DAY17/BOJ_11399.py
- JY/DAY17/BOJ_1476.py
- JY/DAY17/BOJ_1744.py
- JY/DAY18/BOJ_1107.py
- JY/DAY18/BOJ_11576.py
- JY/DAY18/BOJ_1978.py
> [JY] DAY17: 완전탐색, 그리디

- JY/DAY19/BOJ_1929.py
- JY/DAY19/BOJ_6588.py
> [JY] DAY19 : Mathematics

- JY/DAY20/BOJ_10819.py
- JY/DAY20/BOJ_10819_2.py
- JY/DAY20/BOJ_10872.py
- JY/DAY20/BOJ_1451.py
- JY/DAY20/BOJ_1676.py
- JY/DAY20/BOJ_2004.py
> [JY]DAY20:Mathematics, 완전탐색

- JY/DAY21/BOJ_10971.py
- JY/DAY21/BOJ_10971_2.py
- JY/DAY21/BOJ_15649.py
- JY/DAY21/BOJ_15650.py
> [JY]DAY 21: 완전탐색

- JY/DAY21/BOJ_1697.py
- JY/DAY22/BOJ_1963.py
- JY/DAY22/BOJ_1987.py
> [JY]DAY 22 : 완전탐색

- JY/DAY22/BOJ_1987.py
- JY/DAY22/BOJ_9019.py
- JY/DAY23/BOJ_10951.py
- JY/DAY23/BOJ_10952.py
- JY/DAY23/BOJ_10953.py
- JY/DAY23/BOJ_10991.py
- JY/DAY23/BOJ_10992.py
> [JY]DAY23 : 입출력

- JY/DAY24/BOJ_2438.py
- JY/DAY24/BOJ_2439.py
- JY/DAY24/BOJ_2446.py
> [JY]DAY 24 : 입출력

- JY/DAY25/BOJ_1525.py
> [JY]DAY 25 : 완전탐색

- JY/DAY26/BOJ_2003.py
- JY/DAY26/BOJ_2447.py
- JY/DAY26/BOJ_2448.py
> [JY]DAY 26 : 분할정복, 투포인터
